# DefectDojo API 数据源配置
apiVersion: 1

datasources:
  - name: DefectDojo API
    type: marcusolsson-json-datasource
    access: proxy
    url: http://defectdojo:8080
    isDefault: false
    editable: true
    jsonData:
      headers:
        - name: Authorization
          value: Token your-defectdojo-api-token
      queryParams:
        - name: format
          value: json
    secureJsonData:
      httpHeaderValue1: Token your-defectdojo-api-token

  - name: PostgreSQL - DefectDojo
    type: postgres
    access: proxy
    url: postgres:5432
    database: defectdojo
    user: defectdojo
    isDefault: true
    editable: true
    jsonData:
      sslmode: disable
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1400
      timescaledb: false
    secureJsonData:
      password: defectdojo

  - name: PostgreSQL - Grafana
    type: postgres 
    access: proxy
    url: postgres:5432
    database: grafana
    user: defectdojo
    isDefault: false
    editable: true
    jsonData:
      sslmode: disable
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1400
      timescaledb: false
    secureJsonData:
      password: defectdojo