apiVersion: 1

datasources:
  - name: PostgreSQL-Security
    type: postgres
    access: proxy
    url: postgres:5432
    database: defectdojo
    user: defectdojo
    secureJsonData:
      password: defectdojo
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
    isDefault: true
    editable: true